# Generated by Django 5.1.3 on 2024-11-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PandemicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('totalCases', models.IntegerField()),
                ('newCases', models.IntegerField()),
                ('intenciveCareUnit', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('newDeaths', models.IntegerField()),
                ('totalTests', models.IntegerField()),
            ],
        ),
    ]
