# Generated by Django 5.1.3 on 2024-12-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandemicdata',
            name='PCRperDay',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pandemicdata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pandemicdata',
            name='deaths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pandemicdata',
            name='intenciveCareUnit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pandemicdata',
            name='newCases',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pandemicdata',
            name='newDeaths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pandemicdata',
            name='totalCases',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pandemicdata',
            name='totalTests',
            field=models.IntegerField(null=True),
        ),
    ]
